wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.14.0
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.16
    start_time: 1681123733.274111
    t:
      1:
      - 1
      - 5
      - 9
      - 41
      - 53
      - 55
      2:
      - 1
      - 5
      - 9
      - 41
      - 53
      - 55
      3:
      - 1
      - 23
      4: 3.9.16
      5: 0.14.0
      8:
      - 5
